// Title to blog # mapping
const title = {
                "Inspiration": 0,
                "Should Practicality Be a Part of Academia?": 1,
                "Do Our Trainings Determine Our Viewpoint?": 2
              };

const blog = [{
                title: "Inspiration",
                image: "sushant.webp",
                date: "December 27 2021",
                abstract: "“Perhaps, the difference between what is miserable, and that, which is spectacular, lies in the leap of faith… #selfmusing” - Sushant Singh Rajput",
                paragraphs: ["He described himself as “Photon in a double-slit”, Sushant Singh Rajput was an engineer turned actor from a middle-class family in Patna. After his 10th, he went to Delhi where he prepared for JEE at Vidyamandir and FIITJEE hoping to secure a seat in the top engineering colleges of India, which he did. He secured AIR 7th in one of the most competitive entrance examinations, cleared IIT-JEE and also received an admission letter from ISM Dhanbad, before dropping off of college and fighting his way up the Bollywood ladder. Maybe because we have a very similar background, I don’t know, but the star-gazer and physics enthusiast resonates with something in me and makes me feel very positive and motivated when I think about him.",
                "In his speech at IIT Bombay, he talked about the lie that we were told our entire lives that “money + recognition = happiness & success”. “All these years, I was obsessed with what’s going to happen. I was constantly swinging from past to future, not living in an actual sense. And for the first time, in a long time, I understood the true meaning of success, which was not money plus recognition but ‘now’ + ‘excitement’,” he said.",
                "Rajput, which translates to the son of a warrior king, had made a list of what he called “dreams” which he would do, which included things such as train at NASA, send 100 kids for NASA workshop, and learn ‘Polynesian Astronomy’, explore ‘Andromeda’ with a telescope, learn to fly a plane, work for free-education to the underprivileged and more. This inspired me to have a bucket list of my own and motivates me to work towards what makes me happy.",
                "As I write this, his murder mystery is being investigated by the CBI, but whatever be the outcome, he will always be alive in me as my motivation and inspiration."],
                tags: ["Philosophy"]
              },
              {
                title: "Should Practicality Be a Part of Academia?",
                image: "academia.jpeg",
                date: "November 15 2021",
                abstract: "“Education is not the answer to all the questions. Education is the means to answer all questions.”",
                paragraphs: ["William Allin said, 'Education is not the answer to all the questions. Education is the means to answer all questions.' The purpose of Education is to make the disciple ready to face challenges in the real world, and since it is the means to answer all the questions, Education must include all the questions that need to be solved. An academic environment that is isolated would be unaware of social concerns and therefore is of no pragmatic value.",
                             "The purpose of Education is to make the disciple ready to face challenges in the real world, and since it is the means to answer all the questions, Education must include all the questions that need to be solved. An academic environment that is isolated would be unaware of social concerns and therefore is of no pragmatic value.",
                             "Any hypothesis that does not take into consideration the practical aspects of its assumptions is of no use. For example, Dalton's atomic model and plum-pudding model by JJ Thompson, which happen to be the very first models to describe the atom's structure and governance, do not consider the interactions between its constituent particles (electron and proton). These mere-theoretical models are now placed only in the 'history of scientific developments and not in discussions of modern day scientific research, as they serve little purpose in describing the phenomenon they attempted. In High School Chemistry classes, we were taught about ideal gases: gases in the 'perfect’ conditions. But as we reached college, we had to study gases again, this time in real-world conditions as only then could we perform practical experiments and devise something meaningful. This argument that practicality holds utmost importance in any academic discussion holds water in other fields, such as medicine.",
                             "Would someone be qualified as a doctor unless he has studied and looked into an actual human body and not just diagrams of the human anatomy? The self-evident answer to this question provides conclusive evidence on the need to impart practical challenges into academia. In fact, in the medical community, it is considered that the more patients a doctor has served, the more knowledgeable he or she is.",
                             "Tesla has been working on creating a self-driving car since a very long time. They have been working on solving this conundrum for no less than four years now. Despite the theory for creating autonomous cars was published long ago, Tesla has not been able to perfect its model. All Tesla cars come with the notice that the drivers must be alert at all times and have their hands on the steering. It is because only when we test our solutions in the real world and not just simulations, we understand problems that we had not thought of before. The company needs to make sure it has perfected all the real-world situations that the car's intelligent-driver systems can come across to make it completely dependable.",
                             "If we again look at William Allin's saying in this light, we will understand that if Education is the means to answer all questions, it does not make sense if Education is isolated from the questions we are looking to answer. In conclusion, I am in agreement with the view that that we should not isolate the academic world from practical concerns, as ideas that do not subsume practicality are mere hypotheses that hold no meaningful purpose, like a car with wings that cannot fly."],
                tags: ["Philosophy"]
              },
              {
                title: "Do Our Trainings Determine Our Viewpoint?",
                image: "random.jpeg",
                date: "September 08 2018",
                abstract: "“Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired and success achieved.”",
                paragraphs: ["Hellen Keller once said, “Character cannot be developed in ease and quiet. Only through experience of trial and suffering can the soul be strengthened, ambition inspired and success achieved.” Every man on the planet is described by his traits, character or personality and it is the training that a person undergoes that plays an important role in shaping his personality. The statement should have been restated as “The way students and scholars interpret the      materials they work with in their academic fields is a matter of both personality and training. A personality depicted by an individual is a manifestation of the training the person has gone during his upbringing. In other words, a personality and training are not two completely distinct aspects, rather the training of a person determines what personality traits will be demonstrated by that person.",
                "However, it is very true that two persons with two different bents of mind perceive the same thing in a very different manner. For example, the view of a mountain valley can be seen by an aesthete as the beauty of Nature and would appreciate the serenity whereas a pessimist will see the same valley as a vast area of empty land. It is the personality which is the cause of such different views. A terrorist looks at a nuclear source as a weapon of mass destruction while a constructive mind looks at the same nuclear source as a means to provide mankind with a lot of useful energy.",
                "The Vikings used to consider the lunar eclipse to be a werewolf who would eat up the moon and would give a vehement outcry in an attempt to scare away the “deadly creature”, whereas a modern man would now, of course, know about this phenomenon and would act more peacefully that the former. This is because a Viking and a modern man have very different personalities. The modern man has had a much different training than the earlier swordsmen and hence perceives the lunar eclipse to be a natural process and not a mysterious mythological creature.",
                "In stating that “Child is the father of the man”, William Wordsworth implied that there are some innate characteristics that form a part of our personality as we grow up, but it is also true that training also plays a major role in carving out the traits of a person. A student who is in the process of learning things will be incompetent in looking out for meticulous, intricate and minute details while analysing something, while a scholar who has undergone vigorous training will be able look and understand such nuances. Although some inherent qualities might help students overcome some difficulties but won’t allow them to dig through recondite matter.",
                "Therefore I truly believe that both personality and training determine the perspective and are a major driving factor in the viewpoint of any person and it is this perspective that allows one to look at the world in a way others do not see it."],
                tags: ["Philosophy"]
              }
            ]

export { title, blog };
